### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by jaymaart** [Valhalla-Development/ZiplineAutoUpload#1]
Not sure why im getting this. I also tried running cmd as admin and still doesn't work. 

```
C:\Users\jmart\Pictures\zip>py main.py
Monitoring started
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Python312\Lib\site-packages\watchdog\observers\api.py", line 204, in run
    self.dispatch_events(self.event_queue)
  File "C:\Python312\Lib\site-packages\watchdog\observers\api.py", line 380, in dispatch_events
    handler.dispatch(event)
  File "C:\Python312\Lib\site-packages\watchdog\events.py", line 276, in dispatch
    {
  File "C:\Users\jmart\Pictures\zip\main.py", line 35, in on_created
    open(event.src_path, "rb"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:/Users/jmart/Pictures/Screenshots\\Screenshot 2023-12-04 003336.png
```

Code:
```
if __name__ == "__main__":
    # Absolute path to monitor for new files
    path = "C:/Users/jmart/Pictures/Screenshots"
    ```

**Comment by RagnarLothbrok-Odin** [comment]
Hey, thanks for reaching out! I apologize for any inconvenience you may have experienced. Although I don't typically use Windows, I did set up my environment to try and reproduce the error you mentioned. However, I was unable to replicate it. Could you please try the following:

1. Double check your path (`path = "C:/Users/jmart/Pictures/Screenshots"`) and ensure that the folder exists.
2. Set the permissions for the folder. On Windows, you can right-click on the screenshots folder, select properties, then security, and verify that you have the appropriate permissions.
3. Print the `src_path` variable in your `on_created` function by placing a print statement after it, and send me the output.
```python
def on_created(self, event): 
    print(event.src_path) 
    # Array of valid file types
```
This will help us identify any issues with the path or folder permissions.
In the meantime, I will continue to try and replicate the issue you are having.

**Comment by RagnarLothbrok-Odin** [comment]
I wanted to provide a brief update. I've attempted to replicate the error on two different Windows devices without success. However, one of our developers, @iMidnights, has successfully reproduced the error. We are currently in the process of addressing and resolving this issue.

**Comment by RagnarLothbrok-Odin** [comment]
Following our testing, we have identified a solution. We invite you to test it and share your experience with us. We appreciate your feedback on how it performs for you. (e90ad39)
